import fs from 'fs';
import path from 'path';

const fontsDir = path.join(process.cwd(), 'public', 'fonts');
const cssPath = path.join(process.cwd(), 'src', 'app', 'fonts.css');
const configPath = path.join(process.cwd(), 'src', 'config', 'preinstalledFonts.ts');

function detectWeight(filename) {
    const lower = filename.toLowerCase();
    if (lower.includes('thin')) return 100;
    if (lower.includes('extralight') || lower.includes('ultralight')) return 200;
    if (lower.includes('light')) return 300;
    if (lower.includes('medium')) return 500;
    if (lower.includes('semibold') || lower.includes('demibold')) return 600;
    if (lower.includes('extrabold') || lower.includes('ultrabold') || lower.includes('heavy')) return 800;
    if (lower.includes('black') || lower.includes('heavy')) return 900;
    if (lower.includes('bold') || lower.includes('bd')) return 700;
    return 400; // Regular/Normal/Rg
}

function detectStyle(filename) {
    const lower = filename.toLowerCase();
    if (lower.includes('italic') || lower.includes('it')) return 'italic';
    return 'normal';
}

function detectFamily(filename) {
    let name = filename.replace(/\.(ttf|otf|woff|woff2)$/i, '');
    
    // Handle specific Known Yandex cases
    if (name.startsWith('YangoText_')) return 'Yango Text';
    if (name.startsWith('yango-headline')) return 'Yango Headline';
    if (name.startsWith('YSCompressed-')) return 'YS Compressed';
    if (name.startsWith('YSTextDisplayWide-')) return 'YS Text Display Wide';
    
    // Standard YS format: "YS Display-Bold" -> "YS Display"
    if (name.includes('-')) {
        name = name.split('-')[0];
    }
    
    return name.trim();
}

async function run() {
    if (!fs.existsSync(fontsDir)) {
        console.error('fonts directory does not exist');
        return;
    }

    const files = fs.readdirSync(fontsDir).filter(f => /\.(ttf|otf|woff|woff2)$/i.test(f));
    let cssContent = '/* Auto-generated by scripts/generate-fonts.js */\n\n';
    const families = new Set();

    for (const file of files) {
        const family = detectFamily(file);
        families.add(family);
        const weight = detectWeight(file);
        const style = detectStyle(file);
        const format = file.endsWith('.ttf') ? 'truetype' : file.endsWith('.otf') ? 'opentype' : file.endsWith('.woff2') ? 'woff2' : 'woff';

        cssContent += `
@font-face {
    font-family: '${family}';
    src: url('/fonts/${file}') format('${format}');
    font-weight: ${weight};
    font-style: ${style};
    font-display: swap;
}
`;
    }

    const uniqueFamilies = Array.from(families).sort();
    const configContent = `// Auto-generated by scripts/generate-fonts.js
export const PREINSTALLED_FONT_FAMILIES = ${JSON.stringify(uniqueFamilies, null, 4)};\n`;

    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    fs.writeFileSync(cssPath, cssContent);
    fs.writeFileSync(configPath, configContent);

    console.log(`Generated fonts.css with ${files.length} font faces.`);
    console.log(`Exported ${uniqueFamilies.length} font families to preinstalledFonts.ts.`);
}

run();
