"use client";

/**
 * AI Chat Panel — Conversational Agent Interface
 *
 * Full chat interface with:
 * - Message input for natural language requests
 * - Agent orchestration (interprets → plans → executes)
 * - Plan steps with progress indicators
 * - Text/image results with "add to canvas" actions
 */

import { useState, useRef, useEffect } from "react";
import { useCanvasStore } from "@/store/canvasStore";
import { useShallow } from "zustand/react/shallow";
import { getModelsForCaps, getMaxRefs } from "@/lib/ai-models";
import { Button } from "@/components/ui/Button";
import { ReferenceImageInput } from "@/components/ui/ReferenceImageInput";
import { RefAutocompleteTextarea, type RefAutocompleteTextareaHandle } from "@/components/ui/RefAutocompleteTextarea";
import { trpc } from "@/lib/trpc";
import { useWorkspace } from "@/providers/WorkspaceProvider";
import type { Layer, MasterComponent } from "@/types";
import type { TemplatePackV2 } from "@/services/templateService";
import { persistImageToS3 } from "@/utils/imageUpload";
import {
    Copy, Plus, X, Send, Loader2, Bot, User, Sparkles,
    CheckCircle, AlertCircle, ChevronRight, Zap, LayoutTemplate, Search,
    Image as ImageIcon, Type, Settings2, ChevronDown, Repeat
} from "lucide-react";
import type { AIChatMessage } from "./types";
import { MessageBubble } from "./MessageBubble";

/**
 * Wait for Zustand store to have layers populated after template load.
 * Uses subscribe() for reliable detection instead of setTimeout.
 */
function waitForStoreUpdate(timeoutMs = 2000): Promise<void> {
    return new Promise((resolve) => {
        const { useCanvasStore } = require("@/store/canvasStore");
        const currentLayers = useCanvasStore.getState().layers;

        // If layers are already populated, resolve immediately
        if (currentLayers.length > 0) {
            // Still yield to microtask queue so setState fully propagates
            queueMicrotask(resolve);
            return;
        }

        // Subscribe and wait for layers to appear
        const timeout = setTimeout(() => {
            unsub();
            resolve(); // resolve even on timeout to avoid deadlocks
        }, timeoutMs);

        const unsub = useCanvasStore.subscribe((state: { layers: unknown[] }) => {
            if (state.layers.length > 0) {
                clearTimeout(timeout);
                unsub();
                // Yield one more tick so any dependent effects settle
                queueMicrotask(resolve);
            }
        });
    });
}

/**
 * Find a layer by slotId, checking layers directly and via masterComponents.
 */
function findLayerBySlotId(
    slotId: string,
    layers: Layer[],
    masters: MasterComponent[]
): Layer | undefined {
    // Direct match on layer.slotId
    let target = layers.find((l: Layer) => l.slotId === slotId);
    if (target) return target;

    // Match via masterComponent.slotId → layer.masterId
    const mc = masters?.find((m: MasterComponent) => m.slotId === slotId || (m.props as any).slotId === slotId);
    if (mc) {
        target = layers.find((l: Layer) => l.masterId === mc.id);
    }
    return target;
}

export type { AIChatMessage };

interface AIChatPanelProps {
    open: boolean;
    onClose: () => void;
    messages: AIChatMessage[];
    /** Callback to add new messages */
    onAddMessages?: (msgs: AIChatMessage[]) => void;
    /** Current project ID */
    projectId?: string;
}

export function AIChatPanel({ open, onClose, messages, onAddMessages, projectId }: AIChatPanelProps) {
    const { addTextLayer, addImageLayer, layers, updateLayer, canvasWidth, canvasHeight } = useCanvasStore(useShallow((s) => ({
        addTextLayer: s.addTextLayer, addImageLayer: s.addImageLayer,
        layers: s.layers, updateLayer: s.updateLayer,
        canvasWidth: s.canvasWidth, canvasHeight: s.canvasHeight,
    })));
    const { currentWorkspace } = useWorkspace();
    const [input, setInput] = useState("");
    const [isThinking, setIsThinking] = useState(false);
    const [selectedTextModel, setSelectedTextModel] = useState("auto");
    const [selectedImageModel, setSelectedImageModel] = useState("auto");
    const [openDropdown, setOpenDropdown] = useState<"text" | "image" | null>(null);
    const [attachedImages, setAttachedImages] = useState<string[]>([]);
    const scrollRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<RefAutocompleteTextareaHandle>(null);

    // ─── Persistent state across conversation turns ────────
    /** Reference images from the user's original message — persist across template/preset selections */
    const pendingReferenceImages = useRef<string[]>([]);
    /** URL of the last image generated by the agent — reused when applying templates */
    const lastGeneratedImageUrl = useRef<string>("");
    /** Last selected style preset suffix */
    const pendingStyleSuffix = useRef<string>("");

    // Get available models from registry
    const textModels = getModelsForCaps("text");
    const imageModels = getModelsForCaps("generate");

    const agentMutation = trpc.workflow.interpretAndExecute.useMutation();

    // Auto-scroll to bottom
    useEffect(() => {
        if (scrollRef.current) {
            scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
        }
    }, [messages, isThinking]);

    // Focus input on open
    useEffect(() => {
        if (open && inputRef.current) {
            setTimeout(() => inputRef.current?.focus(), 200);
        }
    }, [open]);

    const handleAddToCanvas = async (msg: AIChatMessage) => {
        if (msg.type === "text") {
            addTextLayer({
                text: msg.content,
                fontSize: 40,
                x: 100,
                y: 100,
                width: 600,
            });
        } else if (msg.type === "image") {
            // Persist temporary URL to S3 before adding to canvas
            let src = msg.content;
            if (projectId) {
                try { src = await persistImageToS3(src, projectId); } catch {}
            }
            // Measure actual image size and fit to artboard
            const finalSrc = src;
            const img = new window.Image();
            img.onload = () => {
                let w = img.naturalWidth;
                let h = img.naturalHeight;
                if (w > canvasWidth || h > canvasHeight) {
                    const scaleFactor = Math.min(canvasWidth / w, canvasHeight / h);
                    w = Math.round(w * scaleFactor);
                    h = Math.round(h * scaleFactor);
                }
                addImageLayer(finalSrc, w, h);
            };
            img.onerror = () => addImageLayer(finalSrc, canvasWidth, canvasHeight);
            img.src = finalSrc;
        }
    };

    const handleSend = async () => {
        const trimmed = input.trim();
        if (!trimmed || isThinking || !currentWorkspace) return;

        setInput("");
        setIsThinking(true);

        // Add user message
        const userMsg: AIChatMessage = {
            id: `user-${Date.now()}`,
            role: "user",
            type: "text",
            content: trimmed,
            timestamp: Date.now(),
            attachments: attachedImages.length > 0 ? [...attachedImages] : undefined,
        };

        onAddMessages?.([userMsg]);
        setAttachedImages([]); // Clear attachments after sending

        try {
            // Build conversation history for context
            const history = messages
                .filter((m) => m.type !== "plan")
                .slice(-10)
                .map((m) => ({
                    role: m.role as "user" | "assistant",
                    content: m.content,
                }));

            const result = await agentMutation.mutateAsync({
                message: trimmed,
                workspaceId: currentWorkspace.id,
                projectId,
                history,
                selectedTextModel: selectedTextModel !== "auto" ? selectedTextModel : undefined,
                selectedImageModel: selectedImageModel !== "auto" ? selectedImageModel : undefined,
                referenceImages: userMsg.attachments && userMsg.attachments.length > 0
                    ? userMsg.attachments
                    : undefined,
            });

            // Persist reference images for later turns (template selection, etc.)
            if (userMsg.attachments && userMsg.attachments.length > 0) {
                pendingReferenceImages.current = userMsg.attachments;
            }

            const newMessages: AIChatMessage[] = [];

            // Execute canvas actions — two-phase: load templates first, then update layers
            if (result.canvasActions && result.canvasActions.length > 0) {
                const loadActions = result.canvasActions.filter(ca => ca.action === "load_template");
                const updateActions = result.canvasActions.filter(ca => ca.action === "update_layer");
                const otherActions = result.canvasActions.filter(ca => ca.action !== "load_template" && ca.action !== "update_layer");

                // Phase 1: Execute non-template actions (add_text, add_image)
                for (const ca of otherActions) {
                    if (ca.action === "add_text") {
                        addTextLayer(ca.params as any);
                    } else if (ca.action === "add_image") {
                        const p = ca.params as { src: string; width: number; height: number };
                        let src = p.src;
                        if (projectId) {
                            try { src = await persistImageToS3(src, projectId); } catch {}
                        }
                        addImageLayer(src, p.width, p.height);
                    }
                }

                // Phase 2: Load templates
                for (const ca of loadActions) {
                    const { applyTemplatePack } = await import("@/services/templateService");
                    await applyTemplatePack((ca.params as { templateData: TemplatePackV2 }).templateData);
                }

                // Phase 3: Wait for store to reflect loaded template layers
                if (loadActions.length > 0 && updateActions.length > 0) {
                    await waitForStoreUpdate();
                }

                // Phase 4: Apply update_layer actions (content filling)
                for (const ca of updateActions) {
                    const { slotId, updates } = ca.params as { slotId: string; updates: Record<string, unknown> };
                    const currentLayers = useCanvasStore.getState().layers;
                    const masters = useCanvasStore.getState().masterComponents;
                    const targetLayer = findLayerBySlotId(slotId, currentLayers, masters);
                    if (targetLayer) {
                        updateLayer(targetLayer.id, updates as any);
                    }
                }
            }

            // Add plan message if there are steps
            if (result.plan.steps.length > 0) {
                newMessages.push({
                    id: `plan-${Date.now()}`,
                    role: "assistant",
                    type: "plan",
                    content: result.textResponse,
                    timestamp: Date.now(),
                    steps: result.plan.steps.map((s) => ({
                        actionId: s.actionId,
                        actionName: s.actionName,
                        status: s.status,
                        result: s.result
                            ? { type: s.result.type, content: s.result.content }
                            : undefined,
                    })),
                });

                // Add individual results as separate messages (skip canvas_action, data, template_choices types)
                for (const step of result.plan.steps) {
                    if (step.result?.success && step.result.type !== "error" && step.result.type !== "data") {
                        // Template choices get their own special message
                        if (step.result.type === "template_choices" && step.result.templateChoices) {
                            newMessages.push({
                                id: `templates-${Date.now()}`,
                                role: "assistant",
                                type: "template_choices",
                                content: step.result.content,
                                timestamp: Date.now(),
                                templateChoices: step.result.templateChoices,
                                templateTopic: trimmed, // save original request as topic
                            });
                        } else if (step.result.type === "fallback_actions" && step.result.fallbackActions) {
                            newMessages.push({
                                id: `fallback-${Date.now()}`,
                                role: "assistant",
                                type: "fallback_actions",
                                content: step.result.content,
                                timestamp: Date.now(),
                                fallbackActions: step.result.fallbackActions,
                                templateTopic: trimmed,
                            });
                        } else if (step.result.type === "preset_choices" && step.result.presetChoices) {
                            newMessages.push({
                                id: `presets-${Date.now()}`,
                                role: "assistant",
                                type: "preset_choices",
                                content: step.result.content,
                                timestamp: Date.now(),
                                presetChoices: step.result.presetChoices,
                            });
                        } else if (step.result.type === "canvas_action") {
                            // Check if Market template with text variants
                            const variants = (step.result.metadata as any)?.textVariants;
                            if (variants && Array.isArray(variants) && variants.length > 1) {
                                newMessages.push({
                                    id: `variants-${Date.now()}`,
                                    role: "assistant",
                                    type: "text_variants",
                                    content: step.result.content,
                                    timestamp: Date.now(),
                                    textVariants: variants,
                                    activeVariantIndex: 0,
                                });
                            } else {
                                newMessages.push({
                                    id: `result-${step.actionId}-${Date.now()}-${Math.random()}`,
                                    role: "assistant",
                                    type: "text",
                                    content: step.result.content,
                                    timestamp: Date.now(),
                                });
                            }
                        } else {
                            // Track generated images for template application
                            if (step.result.type === "image" && step.result.content) {
                                // Persist temporary URL to S3 before storing
                                let persistedUrl = step.result.content;
                                if (projectId) {
                                    try { persistedUrl = await persistImageToS3(persistedUrl, projectId); } catch {}
                                }
                                lastGeneratedImageUrl.current = persistedUrl;
                                console.log(`[AIChatPanel] Stored lastGeneratedImageUrl: ${persistedUrl.slice(0, 60)}...`);
                            }
                            newMessages.push({
                                id: `result-${step.actionId}-${Date.now()}-${Math.random()}`,
                                role: "assistant",
                                type: step.result.type as "text" | "image",
                                content: step.result.type === "image" && projectId
                                    ? (await persistImageToS3(step.result.content, projectId).catch(() => step.result!.content))
                                    : step.result.content,
                                timestamp: Date.now(),
                            });
                        }
                    }
                }
            }

            // Add text response if no steps or as summary
            if (result.plan.steps.length === 0 && result.textResponse) {
                newMessages.push({
                    id: `response-${Date.now()}`,
                    role: "assistant",
                    type: "text",
                    content: result.textResponse,
                    timestamp: Date.now(),
                });
            }

            onAddMessages?.(newMessages);
        } catch (e) {
            onAddMessages?.([{
                id: `error-${Date.now()}`,
                role: "assistant",
                type: "error",
                content: e instanceof Error ? e.message : "Ошибка агента",
                timestamp: Date.now(),
            }]);
        } finally {
            setIsThinking(false);
        }
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === "Enter" && !e.shiftKey) {
            e.preventDefault();
            handleSend();
        }
    };

    // Handle fallback action buttons (when no templates found)
    const handleFallbackAction = (actionId: string, topic: string) => {
        if (isThinking || !currentWorkspace) return;

        if (actionId === "create_from_scratch") {
            // Send a request to create banner without templates
            setInput(`Создай баннер с нуля для: ${topic}`);
            setTimeout(() => handleSend(), 50);
        } else if (actionId === "refine_query") {
            // Focus input for user to type a refined query
            setInput("");
            inputRef.current?.focus();
        }
    };

    // Handle variant selection (Market text variants)
    const handleVariantSelect = (msgId: string, variantIndex: number, variant: { title: string; subtitle: string }) => {
        // Update canvas layers
        const currentLayers = useCanvasStore.getState().layers;
        const masters = useCanvasStore.getState().masterComponents;

        // Find and update headline
        const headlineLayer = currentLayers.find((l: Layer) => l.slotId === "headline");
        if (headlineLayer) {
            updateLayer(headlineLayer.id, { text: variant.title } as any);
        } else {
            const headlineMaster = masters?.find((mc: MasterComponent) => mc.slotId === "headline");
            if (headlineMaster) {
                const ml = currentLayers.find((l: Layer) => l.masterId === headlineMaster.id);
                if (ml) updateLayer(ml.id, { text: variant.title } as any);
            }
        }

        // Find and update subhead
        const subheadLayer = currentLayers.find((l: Layer) => l.slotId === "subhead");
        if (subheadLayer) {
            updateLayer(subheadLayer.id, { text: variant.subtitle } as any);
        } else {
            const subheadMaster = masters?.find((mc: MasterComponent) => mc.slotId === "subhead");
            if (subheadMaster) {
                const ml = currentLayers.find((l: Layer) => l.masterId === subheadMaster.id);
                if (ml) updateLayer(ml.id, { text: variant.subtitle } as any);
            }
        }

        // Update active variant in the message
        const updated = messages.map(m =>
            m.id === msgId ? { ...m, activeVariantIndex: variantIndex } : m
        );
        onAddMessages?.(updated.filter(m => !messages.some(old => old.id === m.id)));
        // Use a simple approach: mutate message in place (since messages is passed by reference)
        const targetMsg = messages.find(m => m.id === msgId);
        if (targetMsg) targetMsg.activeVariantIndex = variantIndex;
    };

    // ─── Direct template apply mutation (bypasses LLM) ────────
    const applyTemplateMutation = trpc.workflow.applyTemplate.useMutation();

    // Handle template selection — bypasses LLM, directly applies
    const handleTemplateSelect = (templateId: string, templateName: string, topic: string) => {
        if (isThinking || !currentWorkspace) return;

        setIsThinking(true);

        // Show user message
        onAddMessages?.([{
            id: `user-${Date.now()}`,
            role: "user",
            type: "text",
            content: `Применить шаблон «${templateName}»`,
            timestamp: Date.now(),
        }]);

        // Direct call — no LLM needed, but pass refs for image generation
        applyTemplateMutation.mutateAsync({
            templateId,
            topic,
            workspaceId: currentWorkspace.id,
            selectedImageModel: selectedImageModel !== "auto" ? selectedImageModel : undefined,
            referenceImages: pendingReferenceImages.current.length > 0 ? pendingReferenceImages.current : undefined,
            lastGeneratedImageUrl: lastGeneratedImageUrl.current || undefined,
        }).then(async (result) => {
            // Execute canvas actions — two-phase: load templates first, then update layers
            if (result.canvasActions && result.canvasActions.length > 0) {
                const loadActions = result.canvasActions.filter(ca => ca.action === "load_template");
                const updateActions = result.canvasActions.filter(ca => ca.action === "update_layer");
                const otherActions = result.canvasActions.filter(ca => ca.action !== "load_template" && ca.action !== "update_layer");

                // Phase 1: Other actions
                for (const ca of otherActions) {
                    if (ca.action === "add_text") {
                        addTextLayer(ca.params as any);
                    } else if (ca.action === "add_image") {
                        const p = ca.params as { src: string; width: number; height: number };
                        let src = p.src;
                        if (projectId) {
                            try { src = await persistImageToS3(src, projectId); } catch {}
                        }
                        addImageLayer(src, p.width, p.height);
                    }
                }

                // Phase 2: Load templates
                for (const ca of loadActions) {
                    const { applyTemplatePack } = await import("@/services/templateService");
                    await applyTemplatePack((ca.params as { templateData: TemplatePackV2 }).templateData);
                }

                // Phase 3: Wait for store to reflect loaded template
                if (loadActions.length > 0 && updateActions.length > 0) {
                    await waitForStoreUpdate();
                }

                // Phase 4: Apply update_layer actions
                for (const ca of updateActions) {
                    const { slotId, updates } = ca.params as { slotId: string; updates: Record<string, unknown> };
                    const currentLayers = useCanvasStore.getState().layers;
                    const masters = useCanvasStore.getState().masterComponents;
                    const targetLayer = findLayerBySlotId(slotId, currentLayers, masters);
                    if (targetLayer) {
                        updateLayer(targetLayer.id, updates as any);
                    }
                }
            }

            // Show result
            const newMessages: AIChatMessage[] = [];
            if (result.plan.steps.length > 0) {
                newMessages.push({
                    id: `plan-${Date.now()}`,
                    role: "assistant",
                    type: "plan",
                    content: result.textResponse,
                    timestamp: Date.now(),
                    steps: result.plan.steps.map((s) => ({
                        actionId: s.actionId,
                        actionName: s.actionName,
                        status: s.status,
                        result: s.result
                            ? { type: s.result.type, content: s.result.content }
                            : undefined,
                    })),
                });
            }

            // Check for text variants (Market templates)
            const variants = (result.metadata as any)?.textVariants;
            if (variants && Array.isArray(variants) && variants.length > 1) {
                newMessages.push({
                    id: `variants-${Date.now()}`,
                    role: "assistant",
                    type: "text_variants",
                    content: result.textResponse,
                    timestamp: Date.now(),
                    textVariants: variants,
                    activeVariantIndex: 0,
                });
            } else if (!result.plan.steps.length && result.textResponse) {
                newMessages.push({
                    id: `response-${Date.now()}`,
                    role: "assistant",
                    type: "text",
                    content: result.textResponse,
                    timestamp: Date.now(),
                });
            }

            onAddMessages?.(newMessages);
        }).catch((e) => {
            onAddMessages?.([{
                id: `error-${Date.now()}`,
                role: "assistant",
                type: "error",
                content: e instanceof Error ? e.message : "Ошибка применения шаблона",
                timestamp: Date.now(),
            }]);
        }).finally(() => {
            setIsThinking(false);
        });
    };

    if (!open) return null;

    return (
        <div className="absolute top-3 bottom-3 right-3 w-[360px] bg-bg-surface border border-border-primary rounded-[var(--radius-xl)] shadow-xl z-40 flex flex-col overflow-hidden animate-in slide-in-from-right-4 duration-300">
            {/* Header */}
            <div className="p-4 border-b border-border-primary flex justify-between items-center bg-bg-secondary/50">
                <div className="flex items-center gap-2">
                    <div className="p-1 rounded-lg bg-gradient-to-br from-violet-500/20 to-blue-500/20">
                        <Sparkles size={16} className="text-violet-400" />
                    </div>
                    <h3 className="text-sm font-semibold text-text-primary">AI Ассистент</h3>
                </div>
                <button onClick={onClose} className="text-text-tertiary hover:text-text-primary p-1 rounded-md hover:bg-bg-tertiary cursor-pointer">
                    <X size={16} />
                </button>
            </div>

            {/* Messages */}
            <div ref={scrollRef} className="flex-1 overflow-y-auto p-4 space-y-4">
                {messages.length === 0 && !isThinking ? (
                    <div className="flex flex-col items-center justify-center h-full text-center text-text-tertiary pb-10">
                        <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-violet-500/10 to-blue-500/10 flex items-center justify-center mb-4">
                            <Bot size={24} className="text-violet-400" />
                        </div>
                        <p className="text-sm font-medium text-text-secondary mb-1">AI Ассистент</p>
                        <p className="text-xs max-w-[200px]">
                            Попросите меня создать баннер, сгенерировать текст, или помочь с креативом
                        </p>
                        <div className="mt-4 space-y-1.5 w-full max-w-[220px]">
                            {[
                                "Создай баннер для акции -30%",
                                "Напиши заголовок для промо",
                                "Сгенерируй фото еды",
                            ].map((hint) => (
                                <button
                                    key={hint}
                                    onClick={() => { setInput(hint); inputRef.current?.focus(); }}
                                    className="w-full text-left text-[11px] text-text-tertiary hover:text-text-primary px-3 py-2 rounded-lg bg-bg-tertiary/50 hover:bg-bg-tertiary transition-colors cursor-pointer"
                                >
                                    <ChevronRight size={10} className="inline mr-1.5 opacity-50" />
                                    {hint}
                                </button>
                            ))}
                        </div>
                    </div>
                ) : (
                    messages.map((msg) => (
                        <MessageBubble
                            key={msg.id}
                            msg={msg}
                            onAddToCanvas={() => handleAddToCanvas(msg)}
                            onTemplateSelect={handleTemplateSelect}
                            onFallbackAction={handleFallbackAction}
                            onVariantSelect={handleVariantSelect}
                            onPresetSelect={(presetId, promptSuffix) => {
                                // Save the selected style suffix for downstream use
                                pendingStyleSuffix.current = promptSuffix;
                                // Auto-trigger the next step via agent with style context
                                const presetName = msg.presetChoices?.find(p => p.id === presetId)?.name || "стиль";
                                // Send as a natural follow-up message
                                const followUpMsg = `Используй стиль: ${presetName}`;
                                setInput("");
                                setIsThinking(true);

                                onAddMessages?.([{
                                    id: `user-${Date.now()}`,
                                    role: "user",
                                    type: "text",
                                    content: followUpMsg,
                                    timestamp: Date.now(),
                                }]);

                                // Build history and call agent
                                const history = messages
                                    .filter((m2) => m2.type !== "plan")
                                    .slice(-10)
                                    .map((m2) => ({
                                        role: m2.role as "user" | "assistant",
                                        content: m2.content,
                                    }));

                                agentMutation.mutateAsync({
                                    message: followUpMsg,
                                    workspaceId: currentWorkspace!.id,
                                    projectId,
                                    history,
                                    selectedTextModel: selectedTextModel !== "auto" ? selectedTextModel : undefined,
                                    selectedImageModel: selectedImageModel !== "auto" ? selectedImageModel : undefined,
                                    referenceImages: pendingReferenceImages.current.length > 0 ? pendingReferenceImages.current : undefined,
                                }).then((result) => {
                                    const newMsgs: AIChatMessage[] = [];
                                    let didGenerateImage = false;
                                    // Process results like normal handleSend
                                    if (result.plan.steps.length > 0) {
                                        newMsgs.push({
                                            id: `plan-${Date.now()}`,
                                            role: "assistant",
                                            type: "plan",
                                            content: result.textResponse,
                                            timestamp: Date.now(),
                                            steps: result.plan.steps.map((s) => ({
                                                actionId: s.actionId,
                                                actionName: s.actionName,
                                                status: s.status,
                                                result: s.result ? { type: s.result.type, content: s.result.content } : undefined,
                                            })),
                                        });
                                    }
                                    for (const step of result.plan.steps) {
                                        if (step.result?.success && step.result.type !== "error" && step.result.type !== "data") {
                                            if (step.result.type === "template_choices" && step.result.templateChoices) {
                                                newMsgs.push({
                                                    id: `templates-${Date.now()}`,
                                                    role: "assistant",
                                                    type: "template_choices",
                                                    content: step.result.content,
                                                    timestamp: Date.now(),
                                                    templateChoices: step.result.templateChoices,
                                                    templateTopic: msg.content || "",
                                                });
                                            } else if (step.result.type === "image" && step.result.content) {
                                                lastGeneratedImageUrl.current = step.result.content;
                                                didGenerateImage = true;
                                                newMsgs.push({
                                                    id: `result-${Date.now()}-${Math.random()}`,
                                                    role: "assistant",
                                                    type: "image",
                                                    content: step.result.content,
                                                    timestamp: Date.now(),
                                                });
                                            } else if (step.result.type !== "canvas_action" && step.result.type !== "preset_choices") {
                                                newMsgs.push({
                                                    id: `result-${Date.now()}-${Math.random()}`,
                                                    role: "assistant",
                                                    type: step.result.type as "text" | "image",
                                                    content: step.result.content,
                                                    timestamp: Date.now(),
                                                });
                                            }
                                        }
                                    }
                                    if (result.plan.steps.length === 0 && result.textResponse) {
                                        newMsgs.push({
                                            id: `response-${Date.now()}`,
                                            role: "assistant",
                                            type: "text",
                                            content: result.textResponse,
                                            timestamp: Date.now(),
                                        });
                                    }
                                    onAddMessages?.(newMsgs);

                                    // ── Auto-continue: after image generation → search templates ──
                                    if (didGenerateImage) {
                                        console.log("[AIChatPanel] Image generated, auto-continuing to search_templates...");
                                        const nextMsg = "Теперь найди подходящие шаблоны";
                                        const nextHistory = [
                                            ...history,
                                            { role: "user" as const, content: followUpMsg },
                                            { role: "assistant" as const, content: result.textResponse },
                                            { role: "user" as const, content: nextMsg },
                                        ];

                                        agentMutation.mutateAsync({
                                            message: nextMsg,
                                            workspaceId: currentWorkspace!.id,
                                            projectId,
                                            history: nextHistory,
                                            selectedTextModel: selectedTextModel !== "auto" ? selectedTextModel : undefined,
                                            selectedImageModel: selectedImageModel !== "auto" ? selectedImageModel : undefined,
                                        }).then((templateResult) => {
                                            const templateMsgs: AIChatMessage[] = [];
                                            if (templateResult.plan.steps.length > 0) {
                                                templateMsgs.push({
                                                    id: `plan-tmpl-${Date.now()}`,
                                                    role: "assistant",
                                                    type: "plan",
                                                    content: templateResult.textResponse,
                                                    timestamp: Date.now(),
                                                    steps: templateResult.plan.steps.map((s) => ({
                                                        actionId: s.actionId,
                                                        actionName: s.actionName,
                                                        status: s.status,
                                                        result: s.result ? { type: s.result.type, content: s.result.content } : undefined,
                                                    })),
                                                });
                                            }
                                            for (const step of templateResult.plan.steps) {
                                                if (step.result?.success && step.result.type === "template_choices" && step.result.templateChoices) {
                                                    templateMsgs.push({
                                                        id: `templates-${Date.now()}`,
                                                        role: "assistant",
                                                        type: "template_choices",
                                                        content: step.result.content,
                                                        timestamp: Date.now(),
                                                        templateChoices: step.result.templateChoices,
                                                        templateTopic: msg.content || "",
                                                    });
                                                } else if (step.result?.success && step.result.type !== "error" && step.result.type !== "data" && step.result.type !== "canvas_action") {
                                                    templateMsgs.push({
                                                        id: `result-tmpl-${Date.now()}-${Math.random()}`,
                                                        role: "assistant",
                                                        type: step.result.type as "text",
                                                        content: step.result.content,
                                                        timestamp: Date.now(),
                                                    });
                                                }
                                            }
                                            if (templateResult.plan.steps.length === 0 && templateResult.textResponse) {
                                                templateMsgs.push({
                                                    id: `response-tmpl-${Date.now()}`,
                                                    role: "assistant",
                                                    type: "text",
                                                    content: templateResult.textResponse,
                                                    timestamp: Date.now(),
                                                });
                                            }
                                            onAddMessages?.(templateMsgs);
                                        }).catch((err: Error) => {
                                            onAddMessages?.([{
                                                id: `error-tmpl-${Date.now()}`,
                                                role: "assistant",
                                                type: "error",
                                                content: `Ошибка при поиске шаблонов: ${err.message}`,
                                                timestamp: Date.now(),
                                            }]);
                                        }).finally(() => setIsThinking(false));
                                    } else {
                                        // No auto-continue needed, stop the spinner
                                        setIsThinking(false);
                                    }
                                }).catch((err: Error) => {
                                    onAddMessages?.([{
                                        id: `error-${Date.now()}`,
                                        role: "assistant",
                                        type: "error",
                                        content: err.message || "Ошибка при выполнении",
                                        timestamp: Date.now(),
                                    }]);
                                    setIsThinking(false);
                                });
                            }}
                            isThinking={isThinking}
                        />
                    ))
                )}

                {/* Thinking indicator */}
                {isThinking && (
                    <div className="flex items-start gap-2">
                        <div className="w-7 h-7 rounded-full bg-gradient-to-br from-violet-500/20 to-blue-500/20 flex items-center justify-center shrink-0">
                            <Bot size={14} className="text-violet-400" />
                        </div>
                        <div className="bg-bg-tertiary rounded-2xl rounded-tl-sm px-4 py-3">
                            <div className="flex items-center gap-2">
                                <Loader2 size={14} className="animate-spin text-violet-400" />
                                <span className="text-xs text-text-tertiary">Думаю...</span>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* Model Settings + Input */}
            <div className="border-t border-border-primary bg-bg-secondary/30">
                {/* Model selectors */}
                <div className="px-3 pt-3 flex items-center gap-2 mb-2">
                    <span className="text-[10px] text-text-tertiary flex items-center gap-1">
                        <Settings2 size={11} /> Модели:
                    </span>
                    
                    {/* Text Model Dropdown */}
                    <div className="relative">
                        <button 
                            onClick={() => setOpenDropdown(prev => prev === "text" ? null : "text")}
                            className="flex items-center gap-1.5 px-2 py-1 rounded-md border border-border-primary bg-bg-surface text-[10px] text-text-secondary hover:bg-bg-secondary transition-colors"
                        >
                            <Type size={10} className="text-blue-400" />
                            {selectedTextModel === "auto" ? "Авто" : textModels.find(m => m.id === selectedTextModel)?.label || selectedTextModel}
                            <ChevronDown size={10} />
                        </button>
                        {openDropdown === "text" && (
                            <div className="absolute bottom-full left-0 mb-1 w-[140px] bg-bg-surface border border-border-primary rounded-lg shadow-xl overflow-hidden z-50">
                                <button
                                    onClick={() => { setSelectedTextModel("auto"); setOpenDropdown(null); }}
                                    className={`w-full text-left px-3 py-1.5 text-[10px] hover:bg-bg-secondary ${selectedTextModel === "auto" ? "text-blue-400" : "text-text-secondary"}`}
                                >Авто</button>
                                {textModels.map(m => (
                                    <button
                                        key={m.id}
                                        onClick={() => { setSelectedTextModel(m.id); setOpenDropdown(null); }}
                                        className={`w-full text-left px-3 py-1.5 text-[10px] hover:bg-bg-secondary ${selectedTextModel === m.id ? "text-blue-400" : "text-text-secondary"}`}
                                    >{m.label}</button>
                                ))}
                            </div>
                        )}
                    </div>

                    {/* Image Model Dropdown */}
                    <div className="relative">
                        <button 
                            onClick={() => setOpenDropdown(prev => prev === "image" ? null : "image")}
                            className="flex items-center gap-1.5 px-2 py-1 rounded-md border border-border-primary bg-bg-surface text-[10px] text-text-secondary hover:bg-bg-secondary transition-colors"
                        >
                            <ImageIcon size={10} className="text-violet-400" />
                            {selectedImageModel === "auto" ? "Авто" : imageModels.find(m => m.id === selectedImageModel)?.label || selectedImageModel}
                            <ChevronDown size={10} />
                        </button>
                        {openDropdown === "image" && (
                            <div className="absolute bottom-full left-0 mb-1 w-[140px] bg-bg-surface border border-border-primary rounded-lg shadow-xl overflow-hidden z-50">
                                <button
                                    onClick={() => { setSelectedImageModel("auto"); setOpenDropdown(null); }}
                                    className={`w-full text-left px-3 py-1.5 text-[10px] hover:bg-bg-secondary ${selectedImageModel === "auto" ? "text-violet-400" : "text-text-secondary"}`}
                                >Авто</button>
                                {imageModels.map(m => (
                                    <button
                                        key={m.id}
                                        onClick={() => { setSelectedImageModel(m.id); setOpenDropdown(null); }}
                                        className={`w-full text-left px-3 py-1.5 text-[10px] hover:bg-bg-secondary ${selectedImageModel === m.id ? "text-violet-400" : "text-text-secondary"}`}
                                    >{m.label}</button>
                                ))}
                            </div>
                        )}
                    </div>
                </div>

                {/* Input */}
                <div className="px-3 pb-3">
                    <div className="relative bg-bg-surface border border-border-primary rounded-xl overflow-hidden focus-within:border-violet-500/50 transition-colors">
                        <RefAutocompleteTextarea
                            ref={inputRef}
                            value={input}
                            onChange={setInput}
                            referenceImages={attachedImages}
                            onKeyDown={handleKeyDown}
                            placeholder="Спросите что-нибудь..."
                            rows={3}
                            className="w-full resize-none bg-transparent px-3.5 pt-3 pb-12 text-sm text-text-primary placeholder:text-text-tertiary focus:outline-none min-h-[80px] max-h-[160px] [&::-webkit-scrollbar]:hidden"
                        />
                        
                        <div className="absolute bottom-1.5 left-2 right-1.5 flex items-end justify-between pointer-events-none">
                            <div className="flex-1"></div>
                            <div className="flex items-center gap-1.5 shrink-0 bg-transparent pointer-events-auto">
                                <ReferenceImageInput
                                    images={attachedImages}
                                    onChange={setAttachedImages}
                                    max={selectedImageModel === "auto" ? 14 : (getMaxRefs(selectedImageModel) || 4)}
                                    label=""
                                    onTagClick={(tag) => inputRef.current?.insertAtCursor(tag)}
                                />
                                <button
                                    onClick={handleSend}
                                    disabled={!input.trim() || isThinking}
                                    className="p-1.5 bg-accent-lime-hover hover:bg-accent-lime disabled:opacity-30 disabled:cursor-not-allowed text-accent-lime-text rounded-lg transition-colors cursor-pointer flex items-center justify-center w-8 h-8"
                                >
                                    <Send size={15} className="-ml-0.5" />
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

