// Auto-generated by scripts/generate-fonts.js
export const PREINSTALLED_FONT_FAMILIES = [
    "YS Compressed",
    "YS Display",
    "YS Geo",
    "YS Text",
    "YS Text Cond",
    "YS Text Display Wide",
    "YS Text Wide",
    "Yango Headline",
    "Yango Text"
];
